[package]
name = "ray1_unlocklang"
version = "0.2.0"
authors = ["PluMGMK"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pmw1 = "0.1.0"
